### ISSUE TITLE
Trigger a rebuild of `plugins.prismjs.com` on every change of 11ty-related files

### ISSUE THREAD

**Issue by DmitrySharabin** [PrismJS/website#24]
We can use something like this GitHub action:

```yml
name: Rebuild Plugins Website

on:
  push:
    branches:
      - main
    paths:
      - "_build/**"
      - "_layout/**"
      - "_data/**"

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d '{}' "https://api.netlify.com/build_hooks/BUILD_HOOK?trigger_title=The+main+repo+has+been+updated&clear_cache=true"
```
